![image-20210618161125894](http://mdrs.yuanjin.tech/img/20210618161125.png)

# catch 方法

`.catch(onRejected)` = `.then(null, onRejected)`

# 链式调用

![image-20210621103501094](http://mdrs.yuanjin.tech/img/20210621103501.png)

1. then 方法必定会返回一个新的 Promise

   可理解为`后续处理的返回值也是一个任务`

2. 新任务的状态取决于之前任务后续处理：

   - 若没有相关的后续处理，新任务的状态和前任务一致，数据为前任务的数据

     - 相关的后续处理指：如果前一个任务是 resolve，是成功的，并且有执行 .then 的第一个参数，就是成功和成功相关。如果没有对成功处理，只执行了 .catch, 或者是 .then 的第二个参数，说明只处理了失败的情况，没有处理成功的情况，就是不相关的后续处理。

     ```js
     const pro1 = new Promise((resolve, reject) => {
       reject(1); // pro1 的状态是拒绝
     });
     
     // pro1 并没有对拒绝状态做后续处理
     // 所以 pro2 也是失败状态，
     // pro2.then的第二个参数执行，接收到的参数是1
     const pro2 = pro1.then(() => {
       console.log("pro1 成功状态的后续处理");
     });
     
     pro2.then(
       () => {},
       (error) => {
         console.log(error); // 1
       }
     );
     
     // 如果前一个任务(指pro3)成功了，但是只对前一个任务进行失败处理
     const pro3 = new Promise((resolve, reject) => {
       resolve(1);
     });
     
     // pro4 也是成功状态
     const pro4 = pro3.catch(() => {
       console.log("失败了");
     });
     
     pro4.then((res) => {
       console.log(res); // 1
     });
     ```

     

   

   - 若有后续处理但还未执行，新任务挂起。

     ```js
     const pro1 = new Promise((resolve, reject) => {
       console.log("学习");
       setTimeout(() => {
         resolve();
       }, 2000);
     });
     
     // pro2 是一个新任务， 并且pro1对成功进行了处理
     // 但是因为 pro1 在 2s 之后状态才会发生改变
     // 在pro1 状态改变之前，pro2 一直是 pending，
     const pro2 = pro1.then(() => {
       console.log("考试");
     });
     ```

     

   - 若后续处理执行了，则根据后续处理的情况确定新任务的状态
     - 后续处理执行无错，新任务的状态为完成，数据为后续处理的返回值

       ```js
       new Promise((resolve, reject) => {
         reslove();
       })
         .then(() => {
           // 这个函数没有返回值
           console.log("success");
         })
         .then((res) => {
           console.log(res); // undefined
       
           // 这个函数有返回值
           return 1;
         })
         .then((res) => {
           console.log(res); // 1.
         });
       ```

       

     - 后续处理执行有错，新任务的状态为失败，数据为异常对象

       ```js
       const pro = new Promise((resolve, reject) => {
         reslove();
       })
         .then(() => {
           // 这个函数没有返回值
           console.log("success");
       
           throw new Error("睡着了！！！");
         })
         .catch((error) => {
           console.log(error); // Error: 睡着了！！s！
         });
       
       setTimeout(() => {
         console.log(pro); // resolved 因为 失败被处理了，并且处理的过程没有报过，所以返回的新任务是成功的。
       }, 2000);
       
       pro.then((res) => {
         console.log(res); // undefined 因为 .catch 返回值是undefined
       });
       
       const pro2 = new Promise((resolve, reject) => {
         reject();
       }).catch(() => {
         console.log("处理错误");
         throw 123; // 抛出了一个新的错误
       });
       
       const pro3 = pro2.catch((error) => {
         console.log(error); // 123
         return 456;
       });
       
       setTimeout(() => {
         console.log(pro2); // Promise { <rejected> 123 }
         console.log(pro3); // Promise { 456 } 没有状态，就是成功的意思
       }, 2000);
       ```

       

     - 后续执行后返回的是一个任务对象，新任务的状态和数据与该任务对象一致

       ```js
       const pro = new Promise((res) => {});
       
       const pro2 = new Promise((res) => {
         res();
       }).then(() => {
         return pro;
       });
       // pro2 的状态和 pro 的状态一样。
       // pro 是 pending，pro2就是pending
       // pro 成功，pro2 就成功
       
       new Promise((res) => {
         res();
       })
         .then(() => {
           return new Promise((res) => {
             res(1);
           });
         })
         .then((res) => {
           console.log(res); // 1
         });
       ```



由于链式任务的存在，异步代码拥有了更强的表达力

```js
// 常见任务处理代码

/*
 * 任务成功后，执行处理1，失败则执行处理2
 */
pro.then(处理1).catch(处理2);

/*
 * 任务成功后，依次执行处理1、处理2
 */
pro.then(处理1).then(处理2);

/*
 * 任务成功后，依次执行处理1、处理2，若任务失败或前面的处理有错，执行处理3
 */
pro.then(处理1).then(处理2).catch(处理3);
```

# 邓哥的解决方案

```js
// 向某位女生发送一则表白短信
// name: 女神的姓名
// onFulffiled: 成功后的回调
// onRejected: 失败后的回调
function sendMessage(name) {
  return new Promise((resolve, reject) => {
    // 模拟 发送表白短信
    console.log(
      `邓哥 -> ${name}：最近有谣言说我喜欢你，我要澄清一下，那不是谣言😘`
    );
    console.log(`等待${name}回复......`);
    // 模拟 女神回复需要一段时间
    setTimeout(() => {
      // 模拟 有10%的几率成功
      if (Math.random() <= 0.1) {
        // 成功，调用 onFuffiled，并传递女神的回复
        resolve(`${name} -> 邓哥：我是九，你是三，除了你还是你😘`);
      } else {
        // 失败，调用 onRejected，并传递女神的回复
        reject(`${name} -> 邓哥：你是个好人😜`);
      }
    }, 1000);
  });
}

sendMessage("李建国")
  .catch((reply) => {
    // 失败，继续
    console.log(reply);
    return sendMessage("王富贵");
  })
  .catch((reply) => {
    // 失败，继续
    console.log(reply);
    return sendMessage("周聚财");
  })
  .catch((reply) => {
    // 失败，继续
    console.log(reply);
    return sendMessage("刘人勇");
  })
  .then(
    (reply) => {
      // 成功，结束
      console.log(reply);
      console.log("邓哥终于找到了自己的伴侣");
    },
    (reply) => {
      // 最后一个也失败了
      console.log(reply);
      console.log("邓哥命犯天煞孤星，无伴终老，孤独一生");
    }
  );
```
